# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import salutations_pb2 as salutations__pb2


class salutationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.helloreq = channel.unary_unary(
                '/salutation/helloreq',
                request_serializer=salutations__pb2.helloRequest.SerializeToString,
                response_deserializer=salutations__pb2.helloResponse.FromString,
                )
        self.hellostream = channel.stream_stream(
                '/salutation/hellostream',
                request_serializer=salutations__pb2.helloRequest.SerializeToString,
                response_deserializer=salutations__pb2.helloResponse.FromString,
                )


class salutationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def helloreq(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def hellostream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_salutationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'helloreq': grpc.unary_unary_rpc_method_handler(
                    servicer.helloreq,
                    request_deserializer=salutations__pb2.helloRequest.FromString,
                    response_serializer=salutations__pb2.helloResponse.SerializeToString,
            ),
            'hellostream': grpc.stream_stream_rpc_method_handler(
                    servicer.hellostream,
                    request_deserializer=salutations__pb2.helloRequest.FromString,
                    response_serializer=salutations__pb2.helloResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'salutation', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class salutation(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def helloreq(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/salutation/helloreq',
            salutations__pb2.helloRequest.SerializeToString,
            salutations__pb2.helloResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def hellostream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/salutation/hellostream',
            salutations__pb2.helloRequest.SerializeToString,
            salutations__pb2.helloResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
