# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: salutations.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11salutations.proto\"\x1f\n\x0chelloRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"!\n\rhelloResponse\x12\x10\n\x08messageR\x18\x01 \x01(\t2i\n\nsalutation\x12)\n\x08helloreq\x12\r.helloRequest\x1a\x0e.helloResponse\x12\x30\n\x0bhellostream\x12\r.helloRequest\x1a\x0e.helloResponse(\x01\x30\x01\x62\x06proto3')



_HELLOREQUEST = DESCRIPTOR.message_types_by_name['helloRequest']
_HELLORESPONSE = DESCRIPTOR.message_types_by_name['helloResponse']
helloRequest = _reflection.GeneratedProtocolMessageType('helloRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQUEST,
  '__module__' : 'salutations_pb2'
  # @@protoc_insertion_point(class_scope:helloRequest)
  })
_sym_db.RegisterMessage(helloRequest)

helloResponse = _reflection.GeneratedProtocolMessageType('helloResponse', (_message.Message,), {
  'DESCRIPTOR' : _HELLORESPONSE,
  '__module__' : 'salutations_pb2'
  # @@protoc_insertion_point(class_scope:helloResponse)
  })
_sym_db.RegisterMessage(helloResponse)

_SALUTATION = DESCRIPTOR.services_by_name['salutation']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HELLOREQUEST._serialized_start=21
  _HELLOREQUEST._serialized_end=52
  _HELLORESPONSE._serialized_start=54
  _HELLORESPONSE._serialized_end=87
  _SALUTATION._serialized_start=89
  _SALUTATION._serialized_end=194
# @@protoc_insertion_point(module_scope)
